### ISSUE TITLE
default keyword on class declaration will make webpack go bonkers

### ISSUE THREAD

**Issue by vmachacek** [NetanelBasal/angular2-text-equality-validator#1]
When the class is marked with `default` typescript keyword and I'm trying to build for production.

`ng build --prod` or `ng serve --aot`

will result in 

`ERROR in Unexpected value 'null' exported by the module 'SharedModule in ....shared.module.ts'`

Or I'm missing something?

**Comment by NetanelBasal** [comment]
I released version 2.0.0 without the default, check it.

**Comment by vmachacek** [comment]
Now it says

```
ERROR in Unexpected value 'EqualTextValidator in XXX/node_modules/angular2-text-equality-validator/angular2-text-equality-validator.d.ts' declared by the module 'SharedModule in XXX/app/shared/shared.module.ts'

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'XXX\src'
 @ ./src/main.ts 5:0-74
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.

```

**Comment by NetanelBasal** [comment]
It seems that is not compatible with AOT; I'm sorry I will fix this soon, thanks.

**Comment by rkreutz** [comment]
I'm having the same issue, any updates on this?

Thanks

**Comment by NetanelBasal** [comment]
Try to take the content of the `angular2-text-equality-validator` file to your application without npm and check it again. It's short and plain typescript file.

**Comment by rkreutz** [comment]
Ok, will try that, thanks

**Comment by NetanelBasal** [comment]
I tested this. It will work as a local file. I will fix the package soon.

**Comment by NetanelBasal** [comment]
This library is **deprecated**. Use https://github.com/NetanelBasal/ngx-text-equality-validator instead. Thanks!
