### ISSUE TITLE
The intention is good, but it doesn't work

### ISSUE THREAD

**Issue by ghost** [NetanelBasal/angular2-text-equality-validator#2]
Either it doesn't work, or you've left out some vital information in your documentation.  I've done everything to the letter from your readme, and I'm getting no validation.

Any ideas?

It seems I should be importing something somewhere, but you don't indicate that I need to.

**Comment by NetanelBasal** [comment]
I updated the README file. You should add the directive to your module.

**Comment by ghost** [comment]
Thanks, that's what I needed.
